version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: nettracker-db
    environment:
      POSTGRES_DB: nettracker
      POSTGRES_USER: nettracker
      POSTGRES_PASSWORD: changeme
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
