spring:
  datasource:
    url: jdbc:h2:mem:networth;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
      path: /h2-console
price:
  api:
    base: https://finnhub.io/api/v1/quote
    key: d0uun19r01qmg3uj5fi0d0uun19r01qmg3uj5fig